In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(
    "../Data/raw_ai_student_impact_dataset (1).csv"
)

df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [5]:
df.info()

df.isnull().sum()

df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  str
 2   Year_of_Study               50000 non-null  str
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  str
 6   Prompt_Engineering_Skill    50000 non-null  str
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  str
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  str
dtypes: bool(1), float64(5), int64(4), str(6)
memory usage: 5.8 MB

np.int64(0)

50k rows 16 Columns
0 empty values
0 duplicated

In [6]:
for col in ["Major_Category", "Year_of_Study", "Primary_Use_Case", "Burnout_Risk_Level"]:
    print("\n", col)
    print(df[col].value_counts())

 Major_Category
Major_Category
STEM          15059
Business      12538
Humanities     9994
Medical        6476
Arts           5933
Name: count, dtype: int64

 Year_of_Study
Year_of_Study
Junior       11045
Freshman     11031
Senior       10634
Sophomore     9860
Graduate      7430
Name: count, dtype: int64

 Primary_Use_Case
Primary_Use_Case
Debugging/Troubleshooting    12295
Copywriting/Drafting         12011
Ideation                     10721
Summarizing_Reading           8633
Direct_Answer_Generation      6340
Name: count, dtype: int64

 Burnout_Risk_Level
Burnout_Risk_Level
Medium    21144
Low       16369
High      12487
Name: count, dtype: int64

In [7]:
df["gpa_change"] = (
    df["Post_Semester_GPA"]
    - df["Pre_Semester_GPA"]
)
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level,gpa_change
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High,-0.025
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low,-0.125
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium,0.101
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium,0.211
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium,0.163

In [8]:
# GPA CHANGE PER MAJOR
df.groupby(
    "Major_Category"
)["gpa_change"].mean()

Major_Category
Arts          0.196902
Business      0.194325
Humanities    0.197976
Medical       0.201399
STEM          0.217302
Name: gpa_change, dtype: float64

In [ ]:
#* GPA CHANGE AND RETENTION RATE PER SUBCRIPTION ( FREE OR PAID )
df.groupby(
    "Paid_Subscription"
)[["gpa_change", "Skill_Retention_Score"]].mean()

                   gpa_change  Skill_Retention_Score
Paid_Subscription
False                0.200429              76.072040
True                 0.206971              75.424609

In [10]:
# Average Gpa change of Students who used ai grouped by how many hours do they use ai at a weekly basis 
df.groupby(
    pd.cut(df["Weekly_GenAI_Hours"], bins=5)
)["gpa_change"].agg(["mean", "count"])

                        mean  count
Weekly_GenAI_Hours
(-0.04, 8.0]        0.202014  30762
(8.0, 16.0]         0.228547  11590
(16.0, 24.0]        0.186611   4488
(24.0, 32.0]        0.162135   1854
(32.0, 40.0]        0.121399   1306

In [11]:
# Retention rate of students based on their use of ai weekly
df.groupby(
    pd.cut(df["Weekly_GenAI_Hours"], bins=5)
)["Skill_Retention_Score"].agg(["mean"],)

                         mean
Weekly_GenAI_Hours
(-0.04, 8.0]        76.240489
(8.0, 16.0]         76.952620
(16.0, 24.0]        75.730285
(24.0, 32.0]        68.668711
(32.0, 40.0]        65.487090

In [12]:
df.groupby(
    pd.cut(df["Anxiety_Level_During_Exams"], bins = 10)
)["Weekly_GenAI_Hours"].agg(["mean", "count"])

                                 mean  count
Anxiety_Level_During_Exams
(0.991, 1.9]                 5.999950   5655
(1.9, 2.8]                   6.523216   5752
(2.8, 3.7]                   7.146960   7806
(3.7, 4.6]                   7.809920   8749
(4.6, 5.5]                   8.402976   8222
(5.5, 6.4]                   9.280824   6107
(6.4, 7.3]                  11.118216   3850
(7.3, 8.2]                  12.438616   2088
(8.2, 9.1]                  14.888436   1151
(9.1, 10.0]                 22.802226    620

In [ ]:
# BURNOUT RISK BASED ON AI DEPENDENCY
df.groupby(
    "Burnout_Risk_Level"
    )["Perceived_AI_Dependency"].agg(["mean","count"])

                        mean  count
Burnout_Risk_Level
High                4.641707  12487
Low                 2.819965  16369
Medium              3.364879  21144

In [ ]:
# Does AI dependency affect GPA change within each year?
df.groupby(
    ["Year_of_Study", "Perceived_AI_Dependency"]
)["gpa_change"].agg(["mean", "count"])

                                           mean  count
Year_of_Study Perceived_AI_Dependency
Freshman      1                        0.132312   1640
              2                        0.137003   1976
              3                        0.137934   2305
              4                        0.134351   2197
              5                        0.137520   1457
              6                        0.122538    742
              7                        0.100214    370
              8                        0.085373    209
              9                        0.068409     88
              10                       0.071681     47
Graduate      1                        0.250568   1079
              2                        0.253870   1349
              3                        0.250855   1565
              4                        0.260212   1431
              5                        0.260069    988
              6                        0.242341    545
              7                        0.227826    276
              8                        0.249696    115
              9                        0.190600     65
              10                       0.098824     17
Junior        1                        0.226675   1595
              2                        0.226211   1936
              3                        0.233465   2352
              4                        0.230993   2231
              5                        0.231768   1488
              6                        0.215169    762
              7                        0.192997    382
              8                        0.196430    172
              9                        0.148976     82
              10                       0.133333     45
Senior        1                        0.240647   1599
              2                        0.242339   1890
              3                        0.252439   2231
              4                        0.251553   2055
              5                        0.249581   1420
              6                        0.240004    777
              7                        0.202864    369
              8                        0.168478    180
              9                        0.177400     75
              10                       0.072868     38
Sophomore     1                        0.177289   1390
              2                        0.179334   1723
              3                        0.187330   2025
              4                        0.181690   2020
              5                        0.176720   1392
              6                        0.168423    695
              7                        0.130105    325
              8                        0.147196    179
              9                        0.105706     68
              10                       0.156209     43

In [ ]:
# GPA CHANGE BASED ON THEIR AI DEPENDENCY
df.groupby(
"Perceived_AI_Dependency"
)["gpa_change"].agg(["mean"])

                             mean
Perceived_AI_Dependency
1                        0.202674
2                        0.204884
3                        0.210171
4                        0.208057
5                        0.207944
6                        0.196108
7                        0.168888
8                        0.160255
9                        0.135233
10                       0.108079

In [13]:
df.to_csv(
    "../Data/cleaned_ai_student.csv",
    index=False
)

## Research Questions

### Academic Performance

1. Does increased Generative AI usage relate to higher GPA improvement?
2. Is there an optimal range of weekly AI usage associated with the highest GPA gains?
3. Do students with paid AI subscriptions show different academic outcomes than non-paying students?
4. Does prompt engineering skill relate to better academic performance?
5. Which factors appear most associated with GPA change?

### Learning & Skill Retention

6. Does higher Generative AI usage correspond to lower or higher skill retention?
7. Do students with stronger AI dependency retain skills differently?
8. Does tool diversity influence skill retention outcomes?

### Study Behavior

9. How do traditional study hours compare with Generative AI usage in relation to GPA change?
10. Does combining traditional studying and AI usage produce different outcomes than relying heavily on one approach?
11. How does AI usage vary across different years of study?

### Student Well-being

12. Is higher perceived AI dependency associated with increased burnout risk?
13. Does exam anxiety appear related to increased AI usage?
14. Do students with higher burnout risk show different study patterns?

### Comparative Questions

15. Do outcomes differ across major categories?
16. Which student groups appear to benefit most from Generative AI usage?
17. Are academic improvements consistent across all study years?

### Big Conclusion Question

18. Is moderate Generative AI usage associated with better academic outcomes than excessive usage?